# GitHub Action Part-1 - Basics
name: My-Basics
env:
  APP_NAME: "MY APP"
  PACKAGE_NAME: "flask-deploy-ver -${{ github.sha }}"


on:
  push:
      branches: 
          - main
          
jobs:
    myTest:
        runs-on: ubuntu-latest

        steps:
          -  name : Print Hello Message
             run : echo "Hello World"
             
          -  name : List Current Folder
             run  : ls -la
             
          -  name : Git clone my Repo
             uses : actions/checkout@v1
             
          -  name : List Current Folder 2.0
             run  : ls -la
             
          -  name : Execute few commands
             run  : |
                echo "HELLO 1"
                echo "HELLO 2"
                echo "APLLICATION NAME - ${{ env.APP_NAME}}"
        
    myDeploy:
        runs-on: ubuntu-latest
        needs: [myTest]
        
        steps:
          - name: Print Hello Message
            run : echo "Hello World!!"
          
          - name: Printing Deplyoment Package
            run : echo "Deployment Package name is ${{ env.PACKAGE_NAME }}"
          
          - name: Lets check some packages if they are present
            run : | 
                aws --version
                zip --version
