# GitHub Action Part-1 - Basics
name: My-Basics
env:
  APP_NAME: "MY APP"
  PACKAGE_NAME: "flask-deploy-ver -${{ github.sha }}"
  H_COCK: "26cm"
  S_COCK: "10cm"
on:
  push:
      branches: 
          - main
          
jobs:
    myTest:
        runs-on: ubuntu-latest

        steps:
          -  name : Print Hello Message
             run : echo "Hello World"
             
          -  name : List Current Folder
             run  : ls -la
             
          -  name : Git clone my Repo
             uses : actions/checkout@v1
             
          -  name : List Current Folder 2.0
             run  : ls -la
             
          -  name : Execute few commands
             run  : |
                echo "HELLO 1"
                echo "HELLO 2"
                echo "APLLICATION NAME - ${{ env.APP_NAME}}"
        
    myDeploy:
        runs-on: ubuntu-latest
        needs: [myTest]
        env:
          VAR1: "THIS IS JOB LEVEL VARIABLE 1" 
          VAR2: "THIS IS JOB LEVEL VARIABLE 2"
        
        steps:
          - name: Print Job Level Env Variables
            run : |
              echo "VAR1 = ${{ env.VAR1 }}"
              echo "VAR2 = ${{ env.VAR2 }}"
              echo "SUPER LOCAL VAR = $SUPER_LOCAL_VAR"
            env:
              SUPER_LOCAL_VAR: "VARIABLE INSIDE JOB --> INSIDE STEP"
          - name: Print Hello Harut
            run : |
               echo "HARUT NIGGA!!!"
               echo "HARUT'S COCK is  ${{ env.H_COCK }}"
          
          
          
          - name: Print Hello Message
            run : echo "Hello World!!"
          
          - name: Printing Deplyoment Package
            run : echo "Deployment Package name is ${{ env.PACKAGE_NAME }}"
          
          - name: Lets check some packages if they are present
            run : | 
                aws --version
                zip --version
    
    mySamo:
        runs-on: ubuntu-latest
        needs: [myDeploy]
        
        steps:
           - name: Print Samo Cocks parameter
             run : echo "Samo Cocks Size is ${{ env.S_COCK }}"
              
