# GitHub Action Part-1 - Basics
name: My-Basics
env:
  APP_NAME: "MyVAR"
  PACKAGE_NAME: "flask-deploy-ver= ${{ github.sha }}"


on:
  push:
      branches: 
          - main
          
jobs:
    myTest:
        runs-on: ubuntu-latest

        steps:
          -  name : Print Hello Message
             run : echo "Hello World"
             
          -  name : Execute few commands
             run  : |
                echo "HELLO 1"
                echo "HELLO 2"
                echo "APLLICATION NAME - ${{ env.APP_NAME}}"
        
    myDeploy:
        runs-on: ubuntu-latest
        needs: [myTest]
        
        steps:
          - name: Print Hello Message
            run : echo "Hello World!!"
          
          - name: Printing Deplyoment Package
            run : echo "Deployment Package name is ${{ env.PACKAGE_NAME }}"
